# Safety Security and License Configuration file
security:
    ignore-cvss-severity-below: 0 # A severity number between 0 and 10.
    ignore-cvss-unknown-severity: False # True or False.
    ignore-vulnerabilities: # Here you can list multiple specific vulnerabilities you want to ignore
        51457: # vulnerability ID
            reason: There is no fix for the vulnerability yet
            expires: '2022-12-21'
    continue-on-vulnerability-error: False # Suppress non-zero exit codes when vulnerabilities are found. Enable this in pipelines and CI/CD processes if you want to pass builds that have vulnerabilities.