ACR_DOCKER_AUTH_MASTER: &ACR_DOCKER_AUTH
  image: ${AZURE_LOGIN_SERVER_NAME}/she/circleci-build-image
  auth:
    username: ${ACR_REGISTRY_NAME}
    password: ${ACR_PASSWORD}

DOCKER_BUILD_AND_PUSH_PARAMETERS_MASTER: &DOCKER_BUILD_AND_PUSH_PARAMETERS
  image: ${ACR_REPO_BASE}/dhos-users-api
  registry: ${AZURE_LOGIN_SERVER_NAME}
  tag: dev,cb-${CIRCLE_BUILD_NUM},$(git log --pretty=format:'%h' -n 1)

version: 2.1
orbs:
  azure-acr: circleci/azure-acr@0.1.4
  docker: circleci/docker@2.2.0
commands:
  acr-login:
    description: Authenticate into Azure Container Registry service
    steps:
      - run:
          name: Auth with ACR
          command: az acr login -n $ACR_REGISTRY_NAME -u $AZURE_USERNAME -p $AZURE_PASSWORD
jobs:
  test:
    docker:
      - image: cimg/python:3.9
        environment:
          DATABASE_HOST: localhost
          DATABASE_PORT: 5432
      - image: postgres:12-alpine
        environment:
          POSTGRES_USER: dhos-users
          POSTGRES_PASSWORD: TopSecretPassword
          POSTGRES_DB: "dhos-users"
    steps:
      - checkout
      - run:
          name: Create coverage report dir
          command: mkdir -p ${COVERAGE_REPORT_DIR}
      - run: |
          poetry self update --no-ansi
          pip install --upgrade tox
      - run:
          name: Create tox environment
          command: tox -e poetry-install
      - restore_cache:
          keys:
            - v1-poetry-deps-{{ checksum "poetry.lock" }}
            - v1-poetry-deps-
      - run:
          name: Run tox tests
          command: tox -r -e py39
      - save_cache:
          key: v1-poetry-deps-{{ checksum "poetry.lock" }}
          paths:
            - .tox
      - persist_to_workspace:
          root: coverage-reports
          paths:
            - coverage.xml
  integration-test:
    docker:
      - <<: *ACR_DOCKER_AUTH
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
          version: 20.10.7
      - acr-login
      - run:
          name: Run the integration test script
          command: .circleci/run_integration_tests.sh
  deploy-dev:
    docker:
      - <<: *ACR_DOCKER_AUTH
    environment:
      K8S_DEV_DEPLOYMENT_NAME: deployment/dhos-users-api-dep
      ACR_REPO_BASE: dhos
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
          version: 20.10.7
      - acr-login
      - docker/build:
          step-name: Build Docker image for ACR
          <<: *DOCKER_BUILD_AND_PUSH_PARAMETERS
      - docker/push:
          step-name: Push Docker image to ACR
          <<: *DOCKER_BUILD_AND_PUSH_PARAMETERS
workflows:
  version: 2
  build_test_deploy:
    jobs:
      - test:
          context: engineering-build
      - integration-test:
          context: engineering-build
      - deploy-dev:
          context: engineering-build
          requires:
            - test
            - integration-test
          filters:
            branches:
              only:
                - develop
